import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  await prisma.ticket.deleteMany();
  await prisma.event.deleteMany();

  const events = [
    {
      id: 1,
      title: "Concert de Jazz",
      image: "/Evenement1.jpg",
      date: new Date("2027-12-20"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 2,
      title: "Festival Culturel Malgache",
      image: "/Evenement2.jpg",
      date: new Date("2027-12-25"),
      time: "14:00",
      location: "Toamasina",
      category: "Festival",
      organizator: "Malagasy Culture",
      description:
        "Un festival unique célébrant la richesse de la culture malgache.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 3,
      title: "Soirée Rock Fusion",
      image: "/Evenement3.jpg",
      date: new Date("2027-11-15"),
      time: "20:00",
      location: "Antsirabe",
      category: "Concert",
      organizator: "Rock Madagascar",
      description: "Une fusion explosive de rock et de musique traditionnelle.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 4,
      title: "Festival de Danse",
      image: "/Evenement4.jpg",
      date: new Date("2027-10-30"),
      time: "15:00",
      location: "Majunga",
      category: "Festival",
      organizator: "Dance Malagasy",
      description: "Célébration des danses traditionnelles malgaches.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 5,
      title: "Exposition d'Art Contemporain",
      image: "/Evenement5.jpg",
      date: new Date("2027-09-25"),
      time: "10:00",
      location: "Antananarivo",
      category: "Exposition",
      organizator: "Art Mada",
      description:
        "Une exposition mettant en valeur les artistes contemporains malgaches.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 6,
      title: "Concert de Jazz",
      image: "/Evenement6.jpg",
      date: new Date("2027-06-30"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 7,
      title: "Concert de Jazz",
      image: "/Evenement7.jpg",
      date: new Date("2027-12-20"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 8,
      title: "Concert de Jazz",
      image: "/Evenement8.jpg",
      date: new Date("2027-04-20"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 9,
      title: "Concert de Jazz",
      image: "/Evenement9.jpg",
      date: new Date("2027-06-25"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 10,
      title: "Concert de Jazz",
      image: "/Evenement10.jpg",
      date: new Date("2027-06-26"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 11,
      title: "Concert de Jazz",
      image: "/Evenement11.jpg",
      date: new Date("2027-05-01"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 12,
      title: "Concert de Jazz",
      image: "/Evenement12.jpg",
      date: new Date("2027-04-01"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 13,
      title: "Concert de Jazz",
      image: "/Evenement13.jpg",
      date: new Date("2027-05-03"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 14,
      title: "Concert de Jazz",
      image: "/Evenement14.jpg",
      date: new Date("2027-04-21"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 15,
      title: "Concert de Jazz",
      image: "/Evenement15.jpg",
      date: new Date("2027-06-13"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 16,
      title: "Concert de Jazz",
      image: "/Evenement16.jpg",
      date: new Date("2027-05-01"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 17,
      title: "Concert de Jazz",
      image: "/Evenement17.jpg",
      date: new Date("2027-04-12"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 18,
      title: "Concert de Jazz",
      image: "/Evenement18.jpg",
      date: new Date("2027-04-10"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 19,
      title: "Concert de Jazz",
      image: "/Evenement19.jpg",
      date: new Date("2027-05-20"),
      time: "19:30",
      location: "Antananarivo",
      category: "Concert",
      organizator: "Mozika Events",
      description: "Une soirée jazz exceptionnelle avec des artistes locaux.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
    {
      id: 20,
      title: "Concert Traditionnel",
      image: "/Evenement20.jpg",
      date: new Date("2027-08-20"),
      time: "18:30",
      location: "Fianarantsoa",
      category: "Concert",
      organizator: "Traditions Mada",
      description: "Un voyage musical à travers les traditions malgaches.",
      tickets: {
        create: [
          {
            type: "VIP",
            price: 100.0,
            quantity: 20,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
          {
            type: "Standard",
            price: 45.0,
            quantity: 50,
            maxPerUser: 4,
            active: true,
            userId: 1,
          },
          {
            type: "EarlyBird",
            price: 35.0,
            quantity: 30,
            maxPerUser: 2,
            active: true,
            userId: 1,
          },
        ],
      },
    },
  ];

  for (const event of events) {
    const createdEvent = await prisma.event.create({
      data: event,
      include: {
        tickets: true,
      },
    });
    console.log(`Created event: ${event.title} with ID: ${createdEvent.id}`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
