pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Next.js') {
            steps {
                dir('my-app') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('my-app') {
                    sh 'docker compose down || true'
                    sh 'docker compose up -d --build'
                }
            }
        }

    }
}